service: eternal

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"

functions:
  customersSignUp:
    warmup: true
    handler: app/modules/customers/customers-controller.signUp
    events:
      - http:
          path: customers/signup
          method: post
  productsById:
    warmup: true
    handler: app/modules/products/products-controller.byId
    events:
      - http:
          path: products/{id}
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-warmup
